import { 
  UserAccount, 
  SchoolClass, 
  Teacher, 
  Student, 
  Subject, 
  Semester, 
  TeachingAssignment, 
  GradeRecord, 
  StudentRemark, 
  TimetableSlot 
} from './hocBaTypes';

export const INITIAL_SEMESTERS: Semester[] = [
  {
    id: 'sem1',
    name: 'Học kỳ I',
    academicYear: '2024-2025',
    isCurrent: true,
    entryDeadline: '2024-12-30',
    isLocked: false,
  },
  {
    id: 'sem2',
    name: 'Học kỳ II',
    academicYear: '2024-2025',
    isCurrent: false,
    entryDeadline: '2025-05-25',
    isLocked: true,
  },
];

export const INITIAL_SUBJECTS: Subject[] = [
  { id: 'sub_toan', code: 'TOAN', name: 'Toán học', lessonsPerWeek: 4 },
  { id: 'sub_van', code: 'VAN', name: 'Ngữ văn', lessonsPerWeek: 4 },
  { id: 'sub_anh', code: 'ANH', name: 'Tiếng Anh', lessonsPerWeek: 3 },
  { id: 'sub_ly', code: 'LY', name: 'Vật lý', lessonsPerWeek: 2 },
  { id: 'sub_hoa', code: 'HOA', name: 'Hóa học', lessonsPerWeek: 2 },
  { id: 'sub_sinh', code: 'SINH', name: 'Sinh học', lessonsPerWeek: 2 },
  { id: 'sub_su', code: 'SU', name: 'Lịch sử', lessonsPerWeek: 2 },
  { id: 'sub_dia', code: 'DIA', name: 'Địa lý', lessonsPerWeek: 2 },
  { id: 'sub_gdcd', code: 'GDCD', name: 'Giáo dục công dân', lessonsPerWeek: 1 },
  { id: 'sub_tin', code: 'TIN', name: 'Tin học', lessonsPerWeek: 2 },
  { id: 'sub_td', code: 'TD', name: 'Thể dục', lessonsPerWeek: 2 },
];

export const INITIAL_TEACHERS: Teacher[] = [
  {
    id: 'gv01',
    code: 'GV01',
    name: 'Phạm Thị Mai',
    phone: '0912345678',
    email: 'ptmai@thcsminhkhai.edu.vn',
    mainSubjectId: 'sub_toan',
    gender: 'Nữ',
    title: 'Thạc sĩ Toán học - GVCN Lớp 6A1',
  },
  {
    id: 'gv02',
    code: 'GV02',
    name: 'Trần Đức Anh',
    phone: '0923456789',
    email: 'tdanh@thcsminhkhai.edu.vn',
    mainSubjectId: 'sub_van',
    gender: 'Nam',
    title: 'Cử nhân Sư phạm Văn - GVCN Lớp 7A1',
  },
  {
    id: 'gv03',
    code: 'GV03',
    name: 'Hoàng Thu Trang',
    phone: '0934567890',
    email: 'httrang@thcsminhkhai.edu.vn',
    mainSubjectId: 'sub_anh',
    gender: 'Nữ',
    title: 'Thạc sĩ Ngôn ngữ Anh - GVCN Lớp 8A1',
  },
  {
    id: 'gv04',
    code: 'GV04',
    name: 'Nguyễn Tiến Dũng',
    phone: '0945678901',
    email: 'ntdung@thcsminhkhai.edu.vn',
    mainSubjectId: 'sub_ly',
    gender: 'Nam',
    title: 'Cử nhân Vật lý - GVCN Lớp 9A1',
  },
  {
    id: 'gv05',
    code: 'GV05',
    name: 'Vũ Thị Bích',
    phone: '0956789012',
    email: 'vtbich@thcsminhkhai.edu.vn',
    mainSubjectId: 'sub_su',
    gender: 'Nữ',
    title: 'Cử nhân Lịch sử',
  },
];

export const INITIAL_CLASSES: SchoolClass[] = [
  { id: 'class_6a1', name: '6A1', grade: 6, homeroomTeacherId: 'gv01', room: 'P.101 - Tầng 1', academicYear: '2024-2025', studentCount: 4 },
  { id: 'class_6a2', name: '6A2', grade: 6, homeroomTeacherId: 'gv05', room: 'P.102 - Tầng 1', academicYear: '2024-2025', studentCount: 2 },
  { id: 'class_7a1', name: '7A1', grade: 7, homeroomTeacherId: 'gv02', room: 'P.201 - Tầng 2', academicYear: '2024-2025', studentCount: 1 },
  { id: 'class_8a1', name: '8A1', grade: 8, homeroomTeacherId: 'gv03', room: 'P.301 - Tầng 3', academicYear: '2024-2025', studentCount: 1 },
  { id: 'class_9a1', name: '9A1', grade: 9, homeroomTeacherId: 'gv04', room: 'P.401 - Tầng 4', academicYear: '2024-2025', studentCount: 1 },
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'hs6001',
    code: 'HS6001',
    name: 'Nguyễn An Nhiên',
    classId: 'class_6a1',
    dob: '12/04/2013',
    gender: 'Nữ',
    parentName: 'Nguyễn Văn Hoàn',
    parentPhone: '0988111222',
    address: 'Số 15 Lê Lợi, P. Minh Khai',
    conduct: 'Tốt',
  },
  {
    id: 'hs6002',
    code: 'HS6002',
    name: 'Trần Minh Khôi',
    classId: 'class_6a1',
    dob: '05/09/2013',
    gender: 'Nam',
    parentName: 'Trần Đình Trọng',
    parentPhone: '0988333444',
    address: 'Số 42 Hai Bà Trưng, P. Minh Khai',
    conduct: 'Tốt',
  },
  {
    id: 'hs6003',
    code: 'HS6003',
    name: 'Lê Hoàng Nam',
    classId: 'class_6a1',
    dob: '20/11/2013',
    gender: 'Nam',
    parentName: 'Lê Văn Thắng',
    parentPhone: '0988555666',
    address: 'Số 88 Trần Phú, P. Minh Khai',
    conduct: 'Khá',
  },
  {
    id: 'hs6004',
    code: 'HS6004',
    name: 'Phạm Bảo Anh',
    classId: 'class_6a1',
    dob: '18/01/2013',
    gender: 'Nữ',
    parentName: 'Phạm Quốc Bảo',
    parentPhone: '0988777888',
    address: 'Số 03 Nguyễn Du, P. Minh Khai',
    conduct: 'Tốt',
  },
  {
    id: 'hs6005',
    code: 'HS6005',
    name: 'Hoàng Quốc Việt',
    classId: 'class_6a2',
    dob: '10/02/2013',
    gender: 'Nam',
    parentName: 'Hoàng Anh Tuấn',
    parentPhone: '0977112233',
    address: 'Số 10 Lý Thường Kiệt',
    conduct: 'Tốt',
  },
  {
    id: 'hs6006',
    code: 'HS6006',
    name: 'Đặng Thảo Chi',
    classId: 'class_6a2',
    dob: '25/08/2013',
    gender: 'Nữ',
    parentName: 'Đặng Văn Hùng',
    parentPhone: '0977445566',
    address: 'Số 22 Quang Trung',
    conduct: 'Khá',
  },
  {
    id: 'hs7001',
    code: 'HS7001',
    name: 'Vũ Đức Mạnh',
    classId: 'class_7a1',
    dob: '03/03/2012',
    gender: 'Nam',
    parentName: 'Vũ Văn Hùng',
    parentPhone: '0911223344',
    address: 'Số 50 Điện Biên Phủ',
    conduct: 'Tốt',
  },
  {
    id: 'hs8001',
    code: 'HS8001',
    name: 'Đỗ Khánh Linh',
    classId: 'class_8a1',
    dob: '14/10/2011',
    gender: 'Nữ',
    parentName: 'Đỗ Tiến Thành',
    parentPhone: '0922334455',
    address: 'Số 12 Ngô Quyền',
    conduct: 'Tốt',
  },
  {
    id: 'hs9001',
    code: 'HS9001',
    name: 'Bùi Hoàng Long',
    classId: 'class_9a1',
    dob: '08/06/2010',
    gender: 'Nam',
    parentName: 'Bùi Văn Hải',
    parentPhone: '0933445566',
    address: 'Số 99 Hùng Vương',
    conduct: 'Tốt',
  },
];

export const INITIAL_USERS: UserAccount[] = [
  {
    id: 'u_admin',
    username: 'admin',
    password: '123',
    name: 'Thầy Nguyễn Văn Minh (Hiệu trưởng)',
    role: 'admin',
    email: 'admin@thcsminhkhai.edu.vn',
    phone: '0901234567',
  },
  {
    id: 'u_gv01',
    username: 'gv_mai',
    password: '123',
    name: 'Cô Phạm Thị Mai',
    role: 'teacher',
    teacherId: 'gv01',
    email: 'ptmai@thcsminhkhai.edu.vn',
    phone: '0912345678',
  },
  {
    id: 'u_gv02',
    username: 'gv_anh',
    password: '123',
    name: 'Thầy Trần Đức Anh',
    role: 'teacher',
    teacherId: 'gv02',
    email: 'tdanh@thcsminhkhai.edu.vn',
    phone: '0923456789',
  },
  {
    id: 'u_hs6001',
    username: 'hocsinh_nhien',
    password: '123',
    name: 'Phụ huynh em Nguyễn An Nhiên',
    role: 'student',
    studentId: 'hs6001',
    email: 'ph_nhien@gmail.com',
    phone: '0988111222',
  },
  {
    id: 'u_hs6002',
    username: 'hocsinh_khoi',
    password: '123',
    name: 'Phụ huynh em Trần Minh Khôi',
    role: 'student',
    studentId: 'hs6002',
    email: 'ph_khoi@gmail.com',
    phone: '0988333444',
  },
];

export const INITIAL_ASSIGNMENTS: TeachingAssignment[] = [
  // Lớp 6A1
  { id: 'ta1', teacherId: 'gv01', subjectId: 'sub_toan', classId: 'class_6a1', semesterId: 'sem1' },
  { id: 'ta2', teacherId: 'gv02', subjectId: 'sub_van', classId: 'class_6a1', semesterId: 'sem1' },
  { id: 'ta3', teacherId: 'gv03', subjectId: 'sub_anh', classId: 'class_6a1', semesterId: 'sem1' },
  { id: 'ta4', teacherId: 'gv04', subjectId: 'sub_ly', classId: 'class_6a1', semesterId: 'sem1' },
  { id: 'ta5', teacherId: 'gv05', subjectId: 'sub_su', classId: 'class_6a1', semesterId: 'sem1' },
  // Lớp 7A1
  { id: 'ta6', teacherId: 'gv01', subjectId: 'sub_toan', classId: 'class_7a1', semesterId: 'sem1' },
  { id: 'ta7', teacherId: 'gv02', subjectId: 'sub_van', classId: 'class_7a1', semesterId: 'sem1' },
];

// Helper to compute DTB
export function computeDTB(tx1?: number, tx2?: number, tx3?: number, tx4?: number, gk?: number, ck?: number): number | undefined {
  const txScores = [tx1, tx2, tx3, tx4].filter((s): s is number => s !== undefined && !isNaN(s));
  if (txScores.length === 0 || gk === undefined || ck === undefined) return undefined;
  const avgTx = txScores.reduce((a, b) => a + b, 0) / txScores.length;
  const dtb = (avgTx + gk * 2 + ck * 3) / 6;
  return Math.round(dtb * 10) / 10;
}

export const INITIAL_GRADES: GradeRecord[] = [
  // Nguyễn An Nhiên (HS6001 - 6A1)
  {
    id: 'g_nhien_toan',
    studentId: 'hs6001',
    subjectId: 'sub_toan',
    semesterId: 'sem1',
    tx1: 9.0, tx2: 8.5, tx3: 9.5, tx4: 9.0,
    gk: 9.0, ck: 9.5,
    dtb: 9.1,
    teacherNote: 'Học sinh rất thông minh, giải toán nhanh và chính xác.',
    lastUpdated: '15/12/2024',
  },
  {
    id: 'g_nhien_van',
    studentId: 'hs6001',
    subjectId: 'sub_van',
    semesterId: 'sem1',
    tx1: 8.0, tx2: 8.5, tx3: 9.0, tx4: 8.5,
    gk: 8.5, ck: 9.0,
    dtb: 8.7,
    teacherNote: 'Diễn đạt lưu khoát, cảm thụ văn học tốt.',
    lastUpdated: '16/12/2024',
  },
  {
    id: 'g_nhien_anh',
    studentId: 'hs6001',
    subjectId: 'sub_anh',
    semesterId: 'sem1',
    tx1: 9.5, tx2: 10.0, tx3: 9.0, tx4: 9.5,
    gk: 9.5, ck: 10.0,
    dtb: 9.7,
    teacherNote: 'Phát âm chuẩn, giao tiếp Tiếng Anh rất tự tin.',
    lastUpdated: '18/12/2024',
  },
  {
    id: 'g_nhien_ly',
    studentId: 'hs6001',
    subjectId: 'sub_ly',
    semesterId: 'sem1',
    tx1: 8.5, tx2: 9.0, tx3: 8.5, tx4: 9.0,
    gk: 8.5, ck: 9.0,
    dtb: 8.8,
    teacherNote: 'Nắm vững lý thuyết và thực hành tốt.',
    lastUpdated: '17/12/2024',
  },
  {
    id: 'g_nhien_su',
    studentId: 'hs6001',
    subjectId: 'sub_su',
    semesterId: 'sem1',
    tx1: 9.0, tx2: 8.5, tx3: 9.0, tx4: 9.5,
    gk: 9.0, ck: 9.5,
    dtb: 9.2,
    teacherNote: 'Hăng hái phát biểu xây dựng bài.',
    lastUpdated: '19/12/2024',
  },

  // Trần Minh Khôi (HS6002 - 6A1)
  {
    id: 'g_khoi_toan',
    studentId: 'hs6002',
    subjectId: 'sub_toan',
    semesterId: 'sem1',
    tx1: 7.5, tx2: 8.0, tx3: 7.0, tx4: 8.5,
    gk: 8.0, ck: 8.0,
    dtb: 7.9,
    teacherNote: 'Cần cẩn thận hơn trong tính toán.',
    lastUpdated: '15/12/2024',
  },
  {
    id: 'g_khoi_van',
    studentId: 'hs6002',
    subjectId: 'sub_van',
    semesterId: 'sem1',
    tx1: 7.0, tx2: 7.5, tx3: 8.0, tx4: 7.5,
    gk: 7.5, ck: 7.5,
    dtb: 7.5,
    teacherNote: 'Viết văn logic nhưng cần trau dồi vốn từ.',
    lastUpdated: '16/12/2024',
  },
  {
    id: 'g_khoi_anh',
    studentId: 'hs6002',
    subjectId: 'sub_anh',
    semesterId: 'sem1',
    tx1: 8.0, tx2: 8.5, tx3: 8.0, tx4: 8.5,
    gk: 8.0, ck: 8.5,
    dtb: 8.3,
    teacherNote: 'Từ vựng khá tốt.',
    lastUpdated: '18/12/2024',
  },

  // Lê Hoàng Nam (HS6003 - 6A1)
  {
    id: 'g_nam_toan',
    studentId: 'hs6003',
    subjectId: 'sub_toan',
    semesterId: 'sem1',
    tx1: 6.0, tx2: 6.5, tx3: 5.5, tx4: 6.0,
    gk: 6.0, ck: 6.5,
    dtb: 6.2,
    teacherNote: 'Cần chăm chỉ làm bài tập về nhà hơn.',
    lastUpdated: '15/12/2024',
  },
  {
    id: 'g_nam_van',
    studentId: 'hs6003',
    subjectId: 'sub_van',
    semesterId: 'sem1',
    tx1: 6.5, tx2: 6.0, tx3: 6.5, tx4: 7.0,
    gk: 6.5, ck: 6.5,
    dtb: 6.5,
    teacherNote: 'Cần tập trung lắng nghe giảng.',
    lastUpdated: '16/12/2024',
  },

  // Phạm Bảo Anh (HS6004 - 6A1)
  {
    id: 'g_baoanh_toan',
    studentId: 'hs6004',
    subjectId: 'sub_toan',
    semesterId: 'sem1',
    tx1: 8.5, tx2: 9.0, tx3: 8.5, tx4: 9.0,
    gk: 8.5, ck: 9.0,
    dtb: 8.8,
    teacherNote: 'Học tập tích cực, bài làm cẩn thận.',
    lastUpdated: '15/12/2024',
  },
  {
    id: 'g_baoanh_van',
    studentId: 'hs6004',
    subjectId: 'sub_van',
    semesterId: 'sem1',
    tx1: 9.0, tx2: 8.5, tx3: 9.0, tx4: 9.5,
    gk: 9.0, ck: 9.0,
    dtb: 9.0,
    teacherNote: 'Bài viết giàu cảm xúc, có góc nhìn sâu sắc.',
    lastUpdated: '16/12/2024',
  },
];

export const INITIAL_REMARKS: StudentRemark[] = [
  {
    id: 'rem_nhien',
    studentId: 'hs6001',
    semesterId: 'sem1',
    homeroomRemark: 'Em Nguyễn An Nhiên học giỏi toàn diện, gương mẫu, tích cực tham gia các phong trào lớp và trường. Là Lớp trưởng xuất sắc.',
    strengths: 'Thông minh, tự giác, giao tiếp tiếng Anh lưu khoát, năng nổ.',
    weaknesses: 'Cần chú ý giữ gìn sức khỏe trong mùa thi.',
    conduct: 'Tốt',
    updatedAt: '20/12/2024',
  },
  {
    id: 'rem_khoi',
    studentId: 'hs6002',
    semesterId: 'sem1',
    homeroomRemark: 'Học sinh ngoan ngoãn, có tinh thần giúp đỡ bạn bè, học lực Khá.',
    strengths: 'Chăm chỉ, trung thực, đoàn kết với tập thể.',
    weaknesses: 'Đôi lúc còn trình bày cẩu thả trong môn Toán.',
    conduct: 'Tốt',
    updatedAt: '20/12/2024',
  },
  {
    id: 'rem_nam',
    studentId: 'hs6003',
    semesterId: 'sem1',
    homeroomRemark: 'Học sinh có tiến bộ ở nửa sau học kỳ. Cần rèn luyện thêm tính tự giác.',
    strengths: 'Hòa đồng, yêu thích thể thao.',
    weaknesses: 'Còn mất tập trung trong giờ học môn Văn và Toán.',
    conduct: 'Khá',
    updatedAt: '20/12/2024',
  },
  {
    id: 'rem_baoanh',
    studentId: 'hs6004',
    semesterId: 'sem1',
    homeroomRemark: 'Học sinh giỏi, lễ phép, cẩn thận và có trách nhiệm cao với công việc được giao.',
    strengths: 'Cẩn thận, tiếp thu bài nhanh, viết văn hay.',
    weaknesses: 'Nên tích cực phát biểu hơn nữa.',
    conduct: 'Tốt',
    updatedAt: '20/12/2024',
  },
];

export const INITIAL_TIMETABLE: TimetableSlot[] = [
  // Lớp 6A1 - Thứ 2
  { id: 'tt_6a1_t2_1', classId: 'class_6a1', dayOfWeek: 'Thứ 2', period: 1, session: 'Sáng', subjectId: 'sub_gdcd', teacherId: 'gv01', room: 'P.101' },
  { id: 'tt_6a1_t2_2', classId: 'class_6a1', dayOfWeek: 'Thứ 2', period: 2, session: 'Sáng', subjectId: 'sub_toan', teacherId: 'gv01', room: 'P.101' },
  { id: 'tt_6a1_t2_3', classId: 'class_6a1', dayOfWeek: 'Thứ 2', period: 3, session: 'Sáng', subjectId: 'sub_van', teacherId: 'gv02', room: 'P.101' },
  { id: 'tt_6a1_t2_4', classId: 'class_6a1', dayOfWeek: 'Thứ 2', period: 4, session: 'Sáng', subjectId: 'sub_anh', teacherId: 'gv03', room: 'P.101' },

  // Lớp 6A1 - Thứ 3
  { id: 'tt_6a1_t3_1', classId: 'class_6a1', dayOfWeek: 'Thứ 3', period: 1, session: 'Sáng', subjectId: 'sub_toan', teacherId: 'gv01', room: 'P.101' },
  { id: 'tt_6a1_t3_2', classId: 'class_6a1', dayOfWeek: 'Thứ 3', period: 2, session: 'Sáng', subjectId: 'sub_ly', teacherId: 'gv04', room: 'P.101' },
  { id: 'tt_6a1_t3_3', classId: 'class_6a1', dayOfWeek: 'Thứ 3', period: 3, session: 'Sáng', subjectId: 'sub_van', teacherId: 'gv02', room: 'P.101' },
  { id: 'tt_6a1_t3_4', classId: 'class_6a1', dayOfWeek: 'Thứ 3', period: 4, session: 'Sáng', subjectId: 'sub_su', teacherId: 'gv05', room: 'P.101' },

  // Lớp 6A1 - Thứ 4
  { id: 'tt_6a1_t4_1', classId: 'class_6a1', dayOfWeek: 'Thứ 4', period: 1, session: 'Sáng', subjectId: 'sub_anh', teacherId: 'gv03', room: 'P.101' },
  { id: 'tt_6a1_t4_2', classId: 'class_6a1', dayOfWeek: 'Thứ 4', period: 2, session: 'Sáng', subjectId: 'sub_toan', teacherId: 'gv01', room: 'P.101' },
  { id: 'tt_6a1_t4_3', classId: 'class_6a1', dayOfWeek: 'Thứ 4', period: 3, session: 'Sáng', subjectId: 'sub_tin', teacherId: 'gv04', room: 'P.Tin học' },
  { id: 'tt_6a1_t4_4', classId: 'class_6a1', dayOfWeek: 'Thứ 4', period: 4, session: 'Sáng', subjectId: 'sub_td', teacherId: 'gv05', room: 'Sân trường' },

  // Lớp 6A1 - Thứ 5
  { id: 'tt_6a1_t5_1', classId: 'class_6a1', dayOfWeek: 'Thứ 5', period: 1, session: 'Sáng', subjectId: 'sub_van', teacherId: 'gv02', room: 'P.101' },
  { id: 'tt_6a1_t5_2', classId: 'class_6a1', dayOfWeek: 'Thứ 5', period: 2, session: 'Sáng', subjectId: 'sub_van', teacherId: 'gv02', room: 'P.101' },
  { id: 'tt_6a1_t5_3', classId: 'class_6a1', dayOfWeek: 'Thứ 5', period: 3, session: 'Sáng', subjectId: 'sub_toan', teacherId: 'gv01', room: 'P.101' },
  { id: 'tt_6a1_t5_4', classId: 'class_6a1', dayOfWeek: 'Thứ 5', period: 4, session: 'Sáng', subjectId: 'sub_dia', teacherId: 'gv05', room: 'P.101' },

  // Lớp 6A1 - Thứ 6
  { id: 'tt_6a1_t6_1', classId: 'class_6a1', dayOfWeek: 'Thứ 6', period: 1, session: 'Sáng', subjectId: 'sub_anh', teacherId: 'gv03', room: 'P.101' },
  { id: 'tt_6a1_t6_2', classId: 'class_6a1', dayOfWeek: 'Thứ 6', period: 2, session: 'Sáng', subjectId: 'sub_sinh', teacherId: 'gv04', room: 'P.101' },
  { id: 'tt_6a1_t6_3', classId: 'class_6a1', dayOfWeek: 'Thứ 6', period: 3, session: 'Sáng', subjectId: 'sub_ly', teacherId: 'gv04', room: 'P.101' },
  { id: 'tt_6a1_t6_4', classId: 'class_6a1', dayOfWeek: 'Thứ 6', period: 4, session: 'Sáng', subjectId: 'sub_su', teacherId: 'gv05', room: 'P.101' },

  // Lớp 6A1 - Thứ 7
  { id: 'tt_6a1_t7_1', classId: 'class_6a1', dayOfWeek: 'Thứ 7', period: 1, session: 'Sáng', subjectId: 'sub_toan', teacherId: 'gv01', room: 'P.101' },
  { id: 'tt_6a1_t7_2', classId: 'class_6a1', dayOfWeek: 'Thứ 7', period: 2, session: 'Sáng', subjectId: 'sub_van', teacherId: 'gv02', room: 'P.101' },
  { id: 'tt_6a1_t7_3', classId: 'class_6a1', dayOfWeek: 'Thứ 7', period: 3, session: 'Sáng', subjectId: 'sub_td', teacherId: 'gv05', room: 'Sân trường' },
];
